### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by jdd0401** [walking-shadow/Semantic-guidance-and-spatial-localization-network#11]
Sorry to bother you again. I set "save_checkpoint" to true as you said, but why can't pth model and best model be saved? I can't find any files related to these two after it is trained. Looking forward to your recovery!

**Comment by walking-shadow** [comment]
pth文件会保存在两个文件夹里，而不是当前目录下，文件夹的名字如下面的代码所设置，你可以查看运行的代码文件同目录下，有没有相近名字的文件夹，去里面应该就能找到.pth文件了

    checkpoint_path = f'./{dataset_name}_checkpoint/'
    best_f1score_model_path = f'./{dataset_name}_best_f1score_model/'
    best_loss_model_path = f'./{dataset_name}_best_loss_model/'
