### ISSUE TITLE
open-cd support

### ISSUE THREAD

**Issue by likyoo** [walking-shadow/Semantic-guidance-and-spatial-localization-network#14]
Hi, this work seems to be related to Changer, are you interested in participating in the [Open-CD TRP](https://github.com/likyoo/open-cd/tree/main/projects/open-cd_technical_report) program?

**Comment by walking-shadow** [comment]
I am willing to join this program and contribute the code for the SGSLN model. Additionally, I have another project, [RS-Mamba,](https://github.com/walking-shadow/Official_Remote_Sensing_Mamba) which I can also contribute to this program.

**Comment by likyoo** [comment]
太好啦！方便的话可以先加个微信哈~ likyoo7
