### ISSUE TITLE
coding method

### ISSUE THREAD

**Issue by Kent-xiong** [walking-shadow/Semantic-guidance-and-spatial-localization-network#6]
你好，很感谢你贡献这么优秀的文章和代码。我最近在学习您的代码，但我编码能力不太行，有些地方看不懂。我想请教你代码中的channel_split函数为什么要这样写呢，函数注释中的mixture them on channel dimension的mixture 体现在哪里呀

def channel_split(x):
    """Half segment one feature on channel dimension into two features, mixture them on channel dimension,
    and split them into two features."""
    batchsize, num_channels, height, width = x.data.size()
    assert (num_channels % 4 == 0)
    x = x.reshape(batchsize * num_channels // 2, 2, height * width)
    x = x.permute(1, 0, 2)
    x = x.reshape(2, -1, num_channels // 2, height, width)
    return x[0], x[1]

如果是按照下面的写法，与您的代码效果有什么不同呢？
batchsize, num_channels, height, width = x.data.size()
return  x[:,0:num_channels/2,:,:], x[:,num_channels/2:-1,:,:]

还望解惑。

**Comment by walking-shadow** [comment]
你的这种写法是把两个不同的特征直接在通道上拼在了一起，相当于上半部分是一个特征，下半部分是另外一个特征，两个特征在通道上面没有充分混合。因为网络里面使用的都是这种对半切开再拼接起来的半卷积单元，如果不充分混合，每次对半切开得到的都是上半部分的特征和下半部分的特征，它们之间会没有信息交流。
