### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'pin_memeory'

### ISSUE THREAD

**Issue by adleess** [walking-shadow/Semantic-guidance-and-spatial-localization-network#7]
![1704690517640](https://github.com/NJU-LHRS/offical-SGSLN/assets/26036448/88dab0f9-b1b5-4cb3-96e4-a02123057b48)
运行train.py后会报错，想请教是什么原因导致的

**Comment by walking-shadow** [comment]
版本问题导致的，把loader_args里面的ping_memory参数删除即可

**Comment by adleess** [comment]
感谢大佬回复，解决了
