### ISSUE TITLE
Mask interpolate

### ISSUE THREAD

**Issue by Gchang9** [walking-shadow/Semantic-guidance-and-spatial-localization-network#8]
想请教一下，T1 和T2 计算Loss的时候将label插值为原始大小的1/2，注意到您代码中实现用是双线性插值，这样插值出来的mask除了0和1之外还会含有别的值。想请问下对这块的处理有什么说法吗？

**Comment by walking-shadow** [comment]
因为模型最终的结果还是融合分支的输出结果，而不是T1或者T2分支的输出结果，这两个分支也没有能够输出很好的变化检测结果的能力，因此T1和T2分支的监督主要起一个辅助训练作用，它们的标签可以不用是严格二值化的。
同时因为我们只有一个标签，下采样的标签实际上并不是真实的，它的在0到1之间的值实际上反映了一种模糊态，即这个部分无法确定到底是变化的还是没变化的，那么这个部分计算的损失就应该小一点，而不是也把它二值化为1.

**Comment by Gchang9** [comment]
感谢您的回复。
